// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMt6x8dT7_RBLpnbO_GZW4zrpOuOdsSrw',
    appId: '1:641927001428:web:7cfd3b74053f0b900c44c1',
    messagingSenderId: '641927001428',
    projectId: 'futa-map-bd9c9',
    authDomain: 'futa-map-bd9c9.firebaseapp.com',
    storageBucket: 'futa-map-bd9c9.appspot.com',
    measurementId: 'G-LMRSBW0PHL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSTXVztCIo8QofzTaWnxIsa7Ve_avqnq0',
    appId: '1:641927001428:android:72ae8f79a6fa3e880c44c1',
    messagingSenderId: '641927001428',
    projectId: 'futa-map-bd9c9',
    storageBucket: 'futa-map-bd9c9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD13am4sI5b6bfdltExB8AS426_ACtI-0w',
    appId: '1:641927001428:ios:54dc7bcd2db89f4f0c44c1',
    messagingSenderId: '641927001428',
    projectId: 'futa-map-bd9c9',
    storageBucket: 'futa-map-bd9c9.appspot.com',
    iosClientId: '641927001428-k9v2l409oset2o87djoq6kggrvntq1am.apps.googleusercontent.com',
    iosBundleId: 'com.certified.futamap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD13am4sI5b6bfdltExB8AS426_ACtI-0w',
    appId: '1:641927001428:ios:9af87a589f8cbb0d0c44c1',
    messagingSenderId: '641927001428',
    projectId: 'futa-map-bd9c9',
    storageBucket: 'futa-map-bd9c9.appspot.com',
    iosClientId: '641927001428-9a9uttq9ud3mc4vkhpe3hbrhl6ttdf33.apps.googleusercontent.com',
    iosBundleId: 'com.example.futamap.RunnerTests',
  );
}
